name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: windows-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pyswx/
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Update Poetry configuration
        run: C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry config virtualenvs.create false

      - name: Install dependencies
        run: C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry install --sync --no-interaction

      - name: Package project
        run: C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist/