name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    name: Build under windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Update Poetry configuration
        run: C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry config virtualenvs.create false

      - name: Install dependencies
        run: C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry install --sync --no-interaction

      - name: Clean dist folder
        run: |
          if exist dist rmdir /s /q dist

      - name: Build project
        run: C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/

  publish:
    name: Publish under linux
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/project/pyswx/

    permissions:
      id-token: write  # Required for trusted publishing
      contents: read   # Required to read artifacts

    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist/